package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build1'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build1")) {
    triggers {
        remove {
            vcs {
            }
        }
        add {
            finishBuildTrigger {
                buildType = "TcBugMain_Build"
                branchFilter = """
                    +:refs/heads/
                    +:refs/heads/master
                """.trimIndent()
            }
        }
    }

    dependencies {
        add(RelativeId("Build")) {
            snapshot {
            }
        }

    }
}
